import { JetBrains_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
//components
import Header from "@/components/Header";
import Home from "./page";
import BackToTop from "@/components/BackToTop";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});
const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Daïba - Portfolio React",
  description: "Generated by create next app",
  icons: {
    icon: "/window.jpg",
  },
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} ${playfairDisplay.variable}`}>
        <Header />
        <Home />
        <BackToTop />
      </body>
    </html>
  );
}
